server:
  port: 8081
  servlet:
    context-path: /consumer
spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://192.168.1.103:61616
    pool:
      enabled: true
      max-connections: 10

queueName: publish.queue
topicName: publish.topic