spring:
  application:
    name: datasource

  datasource:
    ds1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3316/db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password:
    ds2: # 数据源2
      #driver-class-name: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3326/db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root # 用户名
      password:

server:
  port: 8088

